x11-apps/xinit: fix whitespace

diff --git a/x11-apps/xinit/files/funtoo/startx b/x11-apps/xinit/files/funtoo/startx
--- a/x11-apps/xinit/files/funtoo/startx
+++ b/x11-apps/xinit/files/funtoo/startx
@@ -14,11 +14,8 @@
 unset DBUS_SESSION_BUS_ADDRESS
 unset SESSION_MANAGER
 
-
 userclientrc=$HOME/.xinitrc
 sysclientrc=/etc/X11/xinit/xinitrc
-
-
 userserverrc=$HOME/.xserverrc
 sysserverrc=/etc/X11/xinit/xserverrc
 defaultclient=xterm
@@ -31,201 +28,173 @@ serverargs=""
 
 enable_xauth=1
 
-
-
 whoseargs="client"
-while [ x"$1" != x ]; do
-    case "$1" in
-    # '' required to prevent cpp from treating "/*" as a C comment.
-    /''*|\./''*)
-	if [ "$whoseargs" = "client" ]; then
-	    if [ x"$client" = x ] && [ x"$clientargs" = x ]; then
-		client="$1"
-	    else
-		clientargs="$clientargs $1"
-	    fi
-	else
-	    if [ x"$server" = x ] && [ x"$serverargs" = x ]; then
-		server="$1"
-	    else
-		serverargs="$serverargs $1"
-	    fi
-	fi
-	;;
-    --)
-	whoseargs="server"
-	;;
-    *)
-	if [ "$whoseargs" = "client" ]; then
-	    clientargs="$clientargs $1"
-	else
-	    # display must be the FIRST server argument
-	    if [ x"$serverargs" = x ] && \
-		 expr "$1" : ':[0-9][0-9]*$' > /dev/null 2>&1; then
-		display="$1"
-	    else
-		serverargs="$serverargs $1"
-	    fi
-	fi
-	;;
-    esac
-    shift
+while [ x"$1" != x ]
+do
+	case "$1" in
+		/*|\./*)
+			if [ "$whoseargs" = "client" ]
+			then
+				if [ x"$client" = x ] && [ x"$clientargs" = x ]
+				then
+					client="$1"
+				else
+					clientargs="$clientargs $1"
+				fi
+			else
+				if [ x"$server" = x ] && [ x"$serverargs" = x ]
+				then
+					server="$1"
+				else
+					serverargs="$serverargs $1"
+				fi
+			fi
+			;;
+		--)
+			whoseargs="server"
+			;;
+		*)
+			if [ "$whoseargs" = "client" ]
+			then
+				clientargs="$clientargs $1"
+			else
+				# display must be the FIRST server argument
+				if [ x"$serverargs" = x ] && \
+					expr "$1" : ':[0-9][0-9]*$' > /dev/null 2>&1
+				then
+					display="$1"
+				else
+					serverargs="$serverargs $1"
+				fi
+			fi
+			;;
+	esac
+	shift
 done
 
 # process client arguments
-if [ x"$client" = x ]; then
-    client=$defaultclient
+if [ x"$client" = x ]
+then
+	client=$defaultclient
 
-    # if no client arguments either, use rc file instead
-    if [ x"$clientargs" = x ]; then
-        if [ -f "$userclientrc" ]; then
-            client=$userclientrc
-        elif [ -f "$sysclientrc" ]; then
-            client=$sysclientrc
+	# if no client arguments either, use rc file instead
+	if [ x"$clientargs" = x ]
+	then
+		if [ -f "$userclientrc" ]
+		then
+			client=$userclientrc
+		elif [ -f "$sysclientrc" ]
+		then
+			client=$sysclientrc
+		fi
 
-
-
-
-
-
-        fi
-
-        clientargs=$defaultclientargs
-    fi
+		clientargs=$defaultclientargs
+	fi
 fi
 
 # process server arguments
-if [ x"$server" = x ]; then
-    server=$defaultserver
+if [ x"$server" = x ]
+then
+	server=$defaultserver
 
-    # if no server arguments or display either, use defaults
-    if [ x"$serverargs" = x -a x"$display" = x ]; then
-	# For compatibility reasons, only use xserverrc if there were no server command line arguments
-	if [ -f "$userserverrc" ]; then
-	    server=$userserverrc
-	elif [ -f "$sysserverrc" ]; then
-	    server=$sysserverrc
+	# if no server arguments or display either, use defaults
+	if [ x"$serverargs" = x -a x"$display" = x ]
+	then
+		# For compatibility reasons, only use xserverrc if there were no server command line arguments
+		if [ -f "$userserverrc" ]
+		then
+			server=$userserverrc
+		elif [ -f "$sysserverrc" ]
+		then
+			server=$sysserverrc
+		fi
+
+		serverargs=$defaultserverargs
+		display=$defaultdisplay
 	fi
-
-	serverargs=$defaultserverargs
-	display=$defaultdisplay
-    fi
 fi
 
-if [ x"$enable_xauth" = x1 ] ; then
-    if [ x"$XAUTHORITY" = x ]; then
-        XAUTHORITY=$HOME/.Xauthority
-        export XAUTHORITY
-    fi
+if [ x"$enable_xauth" = x1 ]
+then
+	if [ x"$XAUTHORITY" = x ]
+	then
+		XAUTHORITY=$HOME/.Xauthority
+		export XAUTHORITY
+	fi
 
-    removelist=
+	removelist=
 
-    # set up default Xauth info for this machine
-    case `uname` in
-    Linux*)
-        if [ -z "`hostname --version 2>&1 | grep GNU`" ]; then
-            hostname=`hostname -f`
-        else
-            hostname=`hostname`
-        fi
-        ;;
-    *)
-        hostname=`hostname`
-        ;;
-    esac
+	# set up default Xauth info for this machine
+	case `uname` in
+		Linux*)
+			if [ -z "`hostname --version 2>&1 | grep GNU`" ]
+			then
+				hostname=`hostname -f`
+			else
+				hostname=`hostname`
+			fi
+			;;
+		*)
+			hostname=`hostname`
+			;;
+	esac
 
-    authdisplay=${display:-:0}
+	authdisplay=${display:-:0}
 
-    mcookie=`/usr/bin/mcookie`
+	mcookie=`/usr/bin/mcookie`
 
+	if test x"$mcookie" = x
+	then
+		echo "Couldn't create cookie"
+		exit 1
+	fi
+	dummy=0
 
-
-
-
-
-
-    if test x"$mcookie" = x; then
-        echo "Couldn't create cookie"
-        exit 1
-    fi
-    dummy=0
-
-    # create a file with auth information for the server. ':0' is a dummy.
-    xserverauthfile=$HOME/.serverauth.$$
-    trap "rm -f '$xserverauthfile'" HUP INT QUIT ILL TRAP KILL BUS TERM
-    xauth -q -f "$xserverauthfile" << EOF
+	# create a file with auth information for the server. ':0' is a dummy.
+	xserverauthfile=$HOME/.serverauth.$$
+	trap "rm -f '$xserverauthfile'" HUP INT QUIT ILL TRAP KILL BUS TERM
+	xauth -q -f "$xserverauthfile" << EOF
 add :$dummy . $mcookie
 EOF
 
+serverargs=${serverargs}" -auth "${xserverauthfile}
 
-
-
-    serverargs=${serverargs}" -auth "${xserverauthfile}
-
-
-    # now add the same credentials to the client authority file
-    # if '$displayname' already exists do not overwrite it as another
-    # server man need it. Add them to the '$xserverauthfile' instead.
-    for displayname in $authdisplay $hostname$authdisplay; do
-        authcookie=`xauth list "$displayname" \
-        | sed -n "s/.*$displayname[[:space:]*].*[[:space:]*]//p"` 2>/dev/null;
-        if [ "z${authcookie}" = "z" ] ; then
-            xauth -q << EOF 
+# now add the same credentials to the client authority file
+# if '$displayname' already exists do not overwrite it as another
+# server man need it. Add them to the '$xserverauthfile' instead.
+for displayname in $authdisplay $hostname$authdisplay
+do
+	authcookie=`xauth list "$displayname" \
+		| sed -n "s/.*$displayname[[:space:]*].*[[:space:]*]//p"` 2>/dev/null;
+	if [ "z${authcookie}" = "z" ]
+	then
+		xauth -q << EOF
 add $displayname . $mcookie
 EOF
-        removelist="$displayname $removelist"
-        else
-            dummy=$(($dummy+1));
-            xauth -q -f "$xserverauthfile" << EOF
+		removelist="$displayname $removelist"
+	else
+		dummy=$(($dummy+1));
+		xauth -q -f "$xserverauthfile" << EOF
 add :$dummy . $authcookie
 EOF
-        fi
-    done
+	fi
+done
 fi
-
-
-
-
-
-
-
-
-
-
-
 
 xinit "$client" $clientargs -- "$server" $display $serverargs
 
-
-
 retval=$?
 
-if [ x"$enable_xauth" = x1 ] ; then
-    if [ x"$removelist" != x ]; then
-        xauth remove $removelist
-    fi
-    if [ x"$xserverauthfile" != x ]; then
-        rm -f "$xserverauthfile"
-    fi
+if [ x"$enable_xauth" = x1 ]
+then
+	if [ x"$removelist" != x ]
+	then
+		xauth remove $removelist
+	fi
+	if [ x"$xserverauthfile" != x ]
+	then
+		rm -f "$xserverauthfile"
+	fi
 fi
 
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
 exit $retval
-
